### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by augustomiller** [mikehoyio/atom-python-black#29]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Zorin OS
**Thrown From**: [python-black](https://github.com/mikehoyio/atom-python-black) package 0.7.0

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:200

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at Object.formatEditor (/packages/python-black/lib/python-black.js:144:22)
    at /packages/python-black/lib/python-black.js:69:16)
    at CommandRegistry.handleCommandEvent (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:351740)
    at CommandRegistry.dispatch (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:11:350215)
    at AtomEnvironment.dispatchApplicationMenuCommand (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:1:786862)
    at EventEmitter.t (/snap/atom/279/usr/share/atom/resources/app/static/<embedded>:1:794833)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
  2x -3:36.5.0 terminus:toggle (atom-pane.pane.active)
     -2:41.9.0 core:backspace (input.hidden-input)
     -1:39.2.0 core:save (input.hidden-input)
     -1:14.5.0 core:move-left (input.hidden-input)
     -0:46.9.0 python-black:format (input.hidden-input)
```

### Non-Core Packages

```
python-black 0.7.0 
terminus 4.1.3 
```

**Comment by iamh2o** [comment]
Same issue

1. Saving from an editor pane

**Atom**: 1.58.0-beta0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [python-black](https://github.com/mikehoyio/atom-python-black) package 0.7.0


### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:200

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at Object.formatEditor (/packages/python-black/lib/python-black.js:144:22)
    at /packages/python-black/lib/python-black.js:69:16)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:352215)
    at CommandRegistry.dispatch (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:350690)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:1:786866)
    at EventEmitter.t (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:1:794837)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
  4x -2:43.5.0 core:move-right (input.hidden-input)
     -2:42.2.0 core:move-left (input.hidden-input)
  3x -2:41.8.0 core:backspace (input.hidden-input)
  6x -2:39.3.0 core:move-down (input.hidden-input)
  3x -2:37.6.0 core:backspace (input.hidden-input)
     -2:33.6.0 intentions:highlight (input.hidden-input)
     -2:33.2.0 core:save (input.hidden-input)
     -2:28.9.0 intentions:highlight (input.hidden-input)
     -2:28.6.0 core:save (input.hidden-input)
     -2:19.3.0 python-black:toggle-format-on-save (input.hidden-input)
  2x -2:17 intentions:highlight (input.hidden-input)
     -2:14.6.0 core:save (input.hidden-input)
     -2:02.7.0 python-black:format (input.hidden-input)
     -1:08.0 intentions:highlight (input.hidden-input)
     -1:07.6.0 core:save (input.hidden-input)
     -0:45.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
acid-syntax 1.0.0 
acido-syntax 0.2.1 
advanced-open-file 0.16.8 
atom-clock 0.1.18 
atom-commander 0.12.3 
atom-distraction-free-ui-theme 2.1.0 
atom-drawio 1.15.0 
atom-html-preview 0.2.6 
atom-hydra 0.3.2 
atom-language-r 1.4.8 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-notes 1.23.0 
atom-toolbar-preferred 1.4.1 
atoms-touchbar 0.4.0 
breakdown 0.90.6 
busy-signal 2.0.1 
data-atom 0.29.1 
data-explorer 0.7.0 
emacs-plus 0.12.0 
emacs-tab 0.2.0 
git-control-fork 0.11.0 
git-projects-manager 1.0.0 
Hydrogen 2.16.3 
hydrogen-auth 0.0.2 
hydrogen-cell-separator 0.4.1 
hydrogen-exectime 0.8.0 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
hydrogen-run 0.1.10 
hydrogen-xdbg 0.0.4 
hyper-alien-ui-theme 0.4.0 
intentions 2.1.1 
ipython-exec 1.2.0 
ipython-run 0.3.1 
kite 0.206.0 
language-atom-notes 0.4.1 
language-r 0.4.2 
linter 3.4.0 
linter-coffeelint 2.0.75 
linter-csslint 2.0.6 
linter-flake8 2.4.0 
linter-htmllint 1.1.14 
linter-js-yaml 1.4.6 
linter-jshint 3.1.19 
linter-jsonlint 1.4.0 
linter-lintr 1.2.0 
linter-shellcheck 1.6.0 
linter-ui-default 3.4.1 
markdown-cell-highlight 1.2.0 
minimap 4.39.14 
minimap-lens 0.8.2 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
moments-atom 0.2.0 
my-package 0.0.0 
no-compromise-ui 0.1.2 
node_modules undefined 
northem-light-atom-ui 2.1.1 
one-dark-syntax-colors-of-the-year-pantone 2.1.0 
organized 0.8.1 
pigments 0.40.6 
project-manager 3.3.8 
python-black 0.7.0 
r24y-touch-bar 0.3.0 
sequence-diagram 0.0.2 
slack-chat 3.4.2 
space-fleet-syntax 1.0.0 
that-syncing-feeling 0.2.0 
theme-alien-syntax 0.6.0 
tool-bar 1.4.4 
tool-bar-almighty 0.9.0 
tool-bar-atom 1.7.1 
tool-bar-markdown 1.0.5 
touchbar-plus 0.3.1 
touchbar-utility 3.3.0 
web-data 0.7.1 
web-lookup 1.3.1 
x-terminal 13.0.10 
```

**Comment by Guhan-SenSam** [comment]
I got the same error. Turns out i had forgot to install python-black in my python virtual venev. Installing it fixed it. Might be what is causing the error.
`pip install black`

**Comment by iamh2o** [comment]
Thanks-  I was still getting accustomed to Atom.  Planning to start from a fresh install soon, I'll see how it goes.

**Comment by AlexKay28** [comment]
This works for me:
1. Install black formatter `pip install black`
2. Figure out the path it was installed in `which black`
3. Define this path in Atom, Settings -> Packages -> Python Black -> Path to the black executable (just "black" there is by default, replace it)

**Comment by AdriandLiu** [comment]
To add precise location of the config file in addition to @AlexKay28 comment, it's .atom -> packages -> python-black -> lib -> python-black.js -> binPath -> default, change it to the path get from `which black`
